git:
  depth: false

matrix:
  include:

###############################################################################
# Service balancer 
###############################################################################
    - os: linux
      dist: bionic
      language: go
       env:
         - TARGET_TYPE=go
         - BUILD_TYPE=Release
         - GOOS=linux
         - GOARCH=amd64
       go:
         - 1.13.x
       install:
         - export BALANCER_PATH=wallet/service-balancer
     script:
         - cd $HOME/build/BeamMW/wallet-service/service-balancer/ && go build
       after_success:
         - tar cvzf service-balancer.tar.gz --directory=$HOME/build/BeamMW/wallet-service/service-balancer/ service-balancer  config.json
         - cd $HOME/build/BeamMW/wallet-service/service-balancer && ls
         - BUILDS_SERVER_PATH=${BUILD_SERVER}/files/$TRAVIS_BRANCH/$(date +%Y.%m.%d)/$BUILD_TYPE/$TARGET_TYPE
         - curl --retry 3 --ftp-create-dirs -T service-balancer.tar.gz $BUILDS_SERVER_PATH/
         - artifacts upload --target-paths "$TRAVIS_BRANCH/$(date +%Y.%m.%d)/$BUILD_TYPE/$TARGET_TYPE/" service-balancer.tar.gz
         - artifacts upload --target-paths "$TRAVIS_BRANCH/latest/$BUILD_TYPE/$TARGET_TYPE/" service-balancer.tar.gz

###############################################################################
# Common part
###############################################################################
before_script:
  - curl -sL https://raw.githubusercontent.com/travis-ci/artifacts/master/install | bash
  - BEAM_TARGET_SUFFIX="-masternet"
  - BEAM_DISPLAY_SUFFIX="Masternet"
  - BEAM_DISPLAY_SUFFIX2="-Masternet"

notifications:
  email:
    - big.romanov@gmail.com
