git:
  depth: false

matrix:
  include:

###############################################################################
# Linux Release
###############################################################################
    - os: linux
      dist: trusty
      language: cpp
      cache: ccache
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - libssl-dev
            - curl
            - libxi-dev
            - libcups2-dev
      install:
        - export TZ=Etc/GMT-3
        # install new version cmake
        - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
        - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}
        - travis_retry wget --no-check-certificate https://github.com/Kitware/CMake/releases/download/v3.14.0/cmake-3.14.0-Linux-x86_64.tar.gz
        - tar -xvf cmake-3.14.0-Linux-x86_64.tar.gz > /dev/null
        - mv cmake-3.14.0-Linux-x86_64 cmake-install
        - PATH=${DEPS_DIR}/cmake-install:${DEPS_DIR}/cmake-install/bin:$PATH
        - cd ${TRAVIS_BUILD_DIR}
        - cmake --version
        - sudo git clone --depth=1 https://github.com/BeamMW/boost-linux.git /usr/local/boost_1_69_0
        - export BOOST_ROOT="/usr/local/boost_1_69_0"
        - eval "CC=gcc-7 && CXX=g++-7"
      env:
        - BUILD_TYPE=Release
        - OS_FOLDER=linux
        - DATE=$(date +%Y.%m.%d)
        - SERVICE_PATH=$HOME/build/BeamMW/wallet-service/service
        - FTP_UPLOAD_PATH=${BUILD_SERVER}/$TRAVIS_BRANCH/$DATE/$BUILD_TYPE/$OS_FOLDER
        - FTP_LATEST_UPLOAD_PATH=${BUILD_SERVER}/$TRAVIS_BRANCH/latest/$BUILD_TYPE/$OS_FOLDER
        - S3_UPLOAD_PATH=$TRAVIS_BRANCH/$DATE/$BUILD_TYPE/$OS_FOLDER
        - S3_LATEST_UPLOAD_PATH=$TRAVIS_BRANCH/latest/$BUILD_TYPE/$OS_FOLDER
      script:
        - cd beam
        - git apply 3rdparty/protobuf-patch.diff
        - cd ..
        - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DDEBUG_MESSAGES_IN_RELEASE_MODE=On -DBEAM_LINK_TYPE=Static -DBRANCH_NAME=$TRAVIS_BRANCH -DBEAM_HW_WALLET=Off .
        - make -j$(nproc)
        # extract build version
        - echo "Main Folder Content" && ls
        - PROJECT_VERSION="$(cat project_version.gen)" && rm project_version.gen
        - echo PROJECT_VERSION = $PROJECT_VERSION
      after_success:
        - SERVICE_ARCHIVE=wallet-service$BEAM_TARGET_SUFFIX-$PROJECT_VERSION.tar.gz
        - SERVICE_ARCHIVE_LATEST=wallet-service$BEAM_TARGET_SUFFIX.tar.gz
        - SBBS_ARCHIVE=sbbs-monitor$BEAM_TARGET_SUFFIX-$PROJECT_VERSION.tar.gz
        - SBBS_ARCHIVE_LATEST=sbbs-monitor$BEAM_TARGET_SUFFIX.tar.gz
        # --- remove this after moving to real testnet ---
        - cd $SERVICE_PATH
        - cp wallet-service-masternet wallet-service-testnet
        - cp sbbs-monitor-masternet sbbs-monitor-testnet
        - cd ${TRAVIS_BUILD_DIR}
        # ------------------------------------------------
        - tar -cvzf $SERVICE_ARCHIVE --directory=$SERVICE_PATH wallet-service$BEAM_TARGET_SUFFIX
        - cp $SERVICE_ARCHIVE $SERVICE_ARCHIVE_LATEST
        - tar -cvzf $SBBS_ARCHIVE --directory=$SERVICE_PATH sbbs-monitor$BEAM_TARGET_SUFFIX
        - cp $SBBS_ARCHIVE $SBBS_ARCHIVE_LATEST
        - echo "Created Archives" && ls *.tar.gz
        # upload to the dated build folder
        - echo $FTP_UPLOAD_PATH
        - echo $S3_UPLOAD_PATH
        - curl --retry 3 --ftp-create-dirs -T $SERVICE_ARCHIVE $FTP_UPLOAD_PATH/$SERVICE_ARCHIVE
        - curl --retry 3 --ftp-create-dirs -T $SBBS_ARCHIVE $FTP_UPLOAD_PATH/$SBBS_ARCHIVE
        - artifacts upload --target-paths "$S3_UPLOAD_PATH" $SERVICE_ARCHIVE
        - artifacts upload --target-paths "$S3_UPLOAD_PATH" $SBBS_ARCHIVE
        # upload to the latest build folder
        - echo $FTP_LATEST_UPLOAD_PATH
        - echo $S3_LATEST_UPLOAD_PATH
        - curl --retry 3 --ftp-create-dirs -T $SERVICE_ARCHIVE_LATEST $FTP_LATEST_UPLOAD_PATH/$SERVICE_ARCHIVE_LATEST
        - curl --retry 3 --ftp-create-dirs -T $SBBS_ARCHIVE_LATEST $FTP_LATEST_UPLOAD_PATH/$SBBS_ARCHIVE_LATEST
        - artifacts upload --target-paths "$S3_LATEST_UPLOAD_PATH" $SERVICE_ARCHIVE_LATEST
        - artifacts upload --target-paths "$S3_LATEST_UPLOAD_PATH" $SBBS_ARCHIVE_LATEST

###############################################################################
# Service Balancer, Linux Release
###############################################################################
    - os: linux
      dist: bionic
      language: go
      env:
         - TARGET_TYPE=go
         - BUILD_TYPE=Release
         - GOOS=linux
         - GOARCH=amd64
         - OS_FOLDER=linux
         - WALLET_SERVICE_PATH=$HOME/build/BeamMW/wallet-service
         - BALANCER_PATH=$WALLET_SERVICE_PATH/service-balancer
         - DATE=$(date +%Y.%m.%d)
         - FTP_UPLOAD_PATH=${BUILD_SERVER}/$TRAVIS_BRANCH/$DATE/$BUILD_TYPE/$OS_FOLDER
         - FTP_LATEST_UPLOAD_PATH=${BUILD_SERVER}/$TRAVIS_BRANCH/latest/$BUILD_TYPE/$OS_FOLDER
         - S3_UPLOAD_PATH=$TRAVIS_BRANCH/$DATE/$BUILD_TYPE/$OS_FOLDER
         - S3_LATEST_UPLOAD_PATH=$TRAVIS_BRANCH/latest/$BUILD_TYPE/$OS_FOLDER
      go:
         - 1.14.x
      before_install:
        - cd $BALANCER_PATH
      script:
         - PROJECT_VERSION=$(cd $WALLET_SERVICE_PATH && bash ./get_balancer_version.sh)
         - echo PROJECT_VERSION=$PROJECT_VERSION
         - cd $BALANCER_PATH && go build -ldflags "-X main.balancerVersion=$PROJECT_VERSION"
      after_success:
         - BALANCER_ARCHIVE=service-balancer$BEAM_TARGET_SUFFIX-$PROJECT_VERSION.tar.gz
         - BALANCER_ARCHIVE_LATEST=service-balancer$BEAM_TARGET_SUFFIX.tar.gz
         - BALANCER_NAME=service-balancer$BEAM_TARGET_SUFFIX
         - cp service-balancer $BALANCER_NAME
         - tar cvzf $BALANCER_ARCHIVE --directory=$BALANCER_PATH $BALANCER_NAME config.json
         - cp $BALANCER_ARCHIVE $BALANCER_ARCHIVE_LATEST
         - echo "Created Archives" && cd $BALANCER_PATH && ls *.tar.gz
         # upload to the dated build folder
         - echo $FTP_UPLOAD_PATH
         - echo $S3_UPLOAD_PATH
         - curl --retry 3 --ftp-create-dirs -T $BALANCER_ARCHIVE $FTP_UPLOAD_PATH/$BALANCER_ARCHIVE
         - artifacts upload --target-paths "$S3_UPLOAD_PATH" $BALANCER_ARCHIVE
         # upload to the latest build folder
         - echo $FTP_LATEST_UPLOAD_PATH
         - curl --retry 3 --ftp-create-dirs -T $BALANCER_ARCHIVE_LATEST $FTP_LATEST_UPLOAD_PATH/$BALANCER_ARCHIVE_LATEST
         - echo S3_LATEST_UPLOAD_PATH
         - artifacts upload --target-paths "$S3_LATEST_UPLOAD_PATH" $BALANCER_ARCHIVE_LATEST

###############################################################################
# Common part
###############################################################################
before_script:
  - curl -sL https://raw.githubusercontent.com/travis-ci/artifacts/master/install | bash
  - BEAM_TARGET_SUFFIX="-testnet"
  - BEAM_DISPLAY_SUFFIX="Testnet"
  - BEAM_DISPLAY_SUFFIX2="-Testnet"

notifications:
  email:
    - big.romanov@gmail.com
