git:
  depth: false

matrix:
  include:

###############################################################################
# Service balancer, linux Release
###############################################################################
    - os: linux
      dist: bionic
      language: go
      env:
         - TARGET_TYPE=go
         - BUILD_TYPE=Release
         - GOOS=linux
         - GOARCH=amd64
         - OS_FOLDER=linux
         - BALANCER_PATH=$HOME/build/BeamMW/wallet-service/service-balancer/
         - DATE=$(date +%Y.%m.%d)
         - FTP_UPLOAD_PATH=${BUILD_SERVER}/$TRAVIS_BRANCH/$DATE/$BUILD_TYPE/$OS_FOLDER/
         - FTP_LATEST_UPLOAD_PATH=${BUILD_SERVER}/$TRAVIS_BRANCH/latest/$BUILD_TYPE/$OS_FOLDER/
         - S3_UPLOAD_PATH=$TRAVIS_BRANCH/$DATE/$BUILD_TYPE/$OS_FOLDER/
         - S3_LATEST_UPLOAD_PATH=$TRAVIS_BRANCH/latest/$BUILD_TYPE/$OS_FOLDER/
      go:
         - 1.14.x
      before_install:
         - cd $BALANCER_PATH
      script:
         - cd $BALANCER_PATH && go build -ldflags "-X main.balancerVersion=N/A"
      after_success:
         - tar cvzf service-balancer.tar.gz --directory=$BALANCER_PATH service-balancer config.json
         - cd $BALANCER_PATH && ls
         - echo $FTP_UPLOAD_PATH
         - curl --retry 3 --ftp-create-dirs -T service-balancer.tar.gz $FTP_UPLOAD_PATH
         - echo $S3_UPLOAD_PATH
         - artifacts upload --target-paths "$S3_UPLOAD_PATH" service-balancer.tar.gz
         - echo S3_LATEST_UPLOAD_PATH
         - artifacts upload --target-paths "$S3_LATEST_UPLOAD_PATH" service-balancer.tar.gz

###############################################################################
# Common part
###############################################################################
before_script:
  - curl -sL https://raw.githubusercontent.com/travis-ci/artifacts/master/install | bash
  - BEAM_TARGET_SUFFIX="-masternet"
  - BEAM_DISPLAY_SUFFIX="Masternet"
  - BEAM_DISPLAY_SUFFIX2="-Masternet"

notifications:
  email:
    - big.romanov@gmail.com
